--- # Poggit-CI Manifest
build-by-default: true
branches:
  - main
projects:
  ScoreHudCoinss:
    path: ""
    libs:
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: "^3.0.0"
      - src: JackMD/ConfigUpdater/ConfigUpdater
        version: "^1.0.0"
...
